### ISSUE TITLE
What does CheckDrive2 do?

### ISSUE THREAD

**Issue by tomcw** [a2-4am/anti-m#33]
I have a query about a change in behaviour in AppleWin when running Anti-M: https://github.com/AppleWin/AppleWin/issues/864

My main question is about this function, `CheckDrive2`:
https://github.com/a2-4am/anti-m/blob/98e587d4d67e316335116a4b071d79c461adfa89/src/anti-m.a#L155

Does this function detect if drive-2 is connected? Or does it detect if a disk is in drive-2?

The README.md says:
>If you launch Anti-M from slot 6 and it detects a disk in drive 2, it will skip the prompt and immediately boot from drive 2.

Is this correct? Or should it be "...and it detects drive 2, ..." ?

**Comment by peterferrie** [comment]
It's intended to detect a disk in drive 2.  If there's either no drive, or no disk in the drive, then the returned value should be a constant (might not even be a full nibble), not changing like in AppleWin.  There can be false-negatives in the detection, depending on where on the disk the head happened to be (i.e. if it's an empty sector, it will have a constant value for a while, too).  This is accepted.

**Comment by tomcw** [comment]
Thanks @peterferrie, I think I know how to handle this now.
