### ISSUE TITLE
CheckDrive2 detects a disk in drive-2 when it's empty, so Anti-M attempts to boot drive-2

### ISSUE THREAD

**Issue by tomcw** [a2-4am/anti-m#34]
Hi @peterferrie,

On my real //e (with drive-2 connected, but empty), Anti-M thinks there's a disk in drive-2 and tries to boot it.

We've been testing the 'no drive' / 'drive empty' behaviour. Our results are over in https://github.com/AppleWin/AppleWin/issues/864#issuecomment-743746897.

In #33, you said about `CheckDrive2`:
> It's intended to detect a disk in drive 2. If there's either no drive, or no disk in the drive, then the returned value should be a constant (might not even be a full nibble)

From our results (on real //e hardware) we see a varying latch value when a drive is connected to real Disk II Interface or Apple 5.25 Controller cards.

**Comment by peterferrie** [comment]
fixed in d3c4100f324a8e886f0effd9ca17688dc82f7c5c

**Comment by tomcw** [comment]
Checking Anti-M v1.9 with AppleWin 1.30.14.1:
1. Default configuration (ie. both drives connected to Disk II card in slot 6) & drive-2 empty: sometimes it'll try to boot from drive-2
   - Repro: just keep pressing F2
2. `applewin.exe -d2-disconnected`: OK - always just boots to "Insert original disk in slot 6 drive 1"

**Comment by peterferrie** [comment]
Bummer.  I was sure that I'd got it right this time.
I will try again.

**Comment by peterferrie** [comment]
ah, AppleWin is randomly returning D5 AA on drive 2, and I forgot to
check more nibbles to reduce the chance of a hit.
